name: Generate Snake

on:
  schedule:
    - cron: "0 0,12 * * *"   
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: snake-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Publish snake files
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake (SVG + dark + GIF)
        uses: Platane/snk@v3
        with:
          github_user_name: karinyalpiano
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
            dist/snake-ocean.gif?color_snake=#22c55e&color_dots=#C0E6FF,#9FD1FF,#7FB6FF,#5D9BFF,#3F84F4

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
          commit_message: "chore: update snake"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
